### ISSUE TITLE
Admin Dashboard on mobile clashes with profile icon

### ISSUE THREAD

**Issue by AlexanderWangY** [swamphacks/HaXr#14]
Profile icon and area still clashes with other elements on mobile in the admin dashboard.

![image](https://github.com/swamphacks/swamp-hacks-system/assets/98280966/901aa18d-dbe5-4698-82ea-b6f895dbafe1)

**Comment by RobertConde** [comment]
This is what I ended up doing for this

<img width="306" alt="image" src="https://github.com/swamphacks/swamp-hacks-system/assets/42223541/282e0aee-3b9d-45a0-98e2-6c7326141a77">

I think we can lose the name and email. Use `hiddenFrom`.

**Comment by AlexanderWangY** [comment]
I dont even think we need the username or email, I think the image is enough and then replace admin with admin portal.
